@localhost=[::1]

GET http://{{localhost}}:3000/ HTTP/1.1


#--------------------------JOBS----------------------------


#----------TÜM İŞLERİ GÖSTER
###
GET http://{{localhost}}:3000/jobs


#----------SPESİFİK İŞ GÖSTER
###
GET http://{{localhost}}:3000/jobs/3


#----------İŞ SİLME
###
DELETE http://{{localhost}}:3000/jobs/4


#----------İŞ YARATMA
###
POST http://{{localhost}}:3000/createjobs
Content-Type: application/json

{
    "jobName": "deneme",
    "jobDescription": "denemeeeeeee"
}

#----------İŞ GÜNCELLEME
###
PATCH http://{{localhost}}:3000/jobs/1
Content-Type: application/json

{
    "jobName": "as",
    "jobDescription": "denemeeeeeee"
}


#--------------------------------------user---------------------------

#----------PROFİL GÖRÜNTÜLEME
###
GET http://{{localhost}}:3000/users/1


#----------PROFİL GÜNCELLEME
###
PATCH http://{{localhost}}:3000/users/1
Content-Type: application/json

{
      "name": "name",
      "lastName": "lastName",
      "email": "email",
      "address": "address",
      "phone": "phone",
      "current_job": "current_job"

}

#----------ŞİFRE DEĞİŞTİRME
###
PATCH http://{{localhost}}:3000/users/resetPassword/1
Content-Type: application/json

{
      "oldPassword": "123456",
      "newPassword1": "furkanbaba",
      "newPassword2": "furkanbaba"   

}



#----------KİŞİNİN KENDİ BAŞVURULARI
###
GET http://{{localhost}}:3000/user/1/applications


#----------İD'Sİ 2 OLAN İŞE BAŞVURSUN İD'Sİ 1 OLAN KULLANICI
###
GET http://{{localhost}}:3000/user/1/apply/2



#----------kullanıcı feedback göndersin
###
POST http://{{localhost}}:3000/user/sendfeedback
Content-Type: application/json

{
      "name": "123456",
      "lastName": "furkanbaba",
      "email": "furkanbaba",
      "detail": "furkanbaba"  

}

#---------------------GUEST-------------------------------


#----------login ol
###
POST http://{{localhost}}:3000/login
Content-Type: application/json

{      
      "email": "email",
      "password": "furkanbaba"     
}

#----------id'si 2 olan işi göster giriş olmadan
###
GET http://{{localhost}}:3000/guest/jobs/2


#----------kayıt ol
###
POST http://{{localhost}}:3000/register
Content-Type: application/json

{
      "name": "mahmut",
      "lastName": "kiraz",
      "email": "abc",
      "address": "address",
      "phone": "0535",
      "current_job": "current_job"
}

#----------feedback gönder giriş yapmadan
###
POST http://{{localhost}}:3000/guest/sendfeedback
Content-Type: application/json

{
      "name": "asd",
      "lastName": "asdasddas",
      "email": "asdasdsda",
      "detail": "asdasdsda"  

}


#-----ADMİN----------ADMİN----------ADMİN----------ADMİN-------ADMİN-----

#----------tüm kullanıcılar
###
GET http://{{localhost}}:3000/admin/users

#----------spesifik kullanıcı
###
GET http://{{localhost}}:3000/admin/users/2

#----------bir işe başvuran tüm kişiler
###
GET http://{{localhost}}:3000/admin/jobs/4/applicants

#----------bir kişinin başvurduğu tüm işler
###
GET http://{{localhost}}:3000/admin/users/1/applications